### ISSUE TITLE
Audio Transients too sharp

### ISSUE THREAD

**Issue by filliptm** [a1lazydog/ComfyUI-AudioScheduler#1]
The problem im having is the scanned transients of audio that are transformed into weight floats are too sharp and die off too quickly. Having something like a release on how quickly the thing collapses to 0 would be super useful. 

Or the ability to essentially compress the audio graph and "Push" it into the top of the graph (weight of 1) so that the tops are clipped. Allowing for more time to pass (more frames to be rendered) that the designated prompt is set as a weight of 1. Iv tried adding a multiplier to the float value to push the prompt weight harder, but the effect i get is the prompt i schedule pops in and out of frames too quickly because there isnt enough frames being rendered with the weight at its maximum value. They die off too quickly because the transients are too sharp

**Comment by a1lazydog** [comment]
That's excellent feedback! I haven't been fully ready to show this repro more publicly just yet since I'm still experimenting with it.

I love the idea of adding a release to it.  The ability to compress, or clip the graph is interesting since that's usually the opposite of what is desired for sound, but since we are using to drive strength, that may be an option.  I was also thinking of adding a compression node with similar features to the ones found on a mixer.

**Comment by filliptm** [comment]
yeah the more audio manipulation tools the better! But yeah, if we're using the audio waves to control parameters around the system, you def need to allow more transient shaping features into it

good job tho bruv, this is sick, if you didnt make this i was prob 1 day away from trying myself =P

**Comment by a1lazydog** [comment]
I added a TransientAmplitudeBasic Node to apply attack, hold and release parameters to the amplitude wave.

I also added a ClipAmplitude to apply clipping to the amplitude wave.
